### ISSUE TITLE
Too much orders?

### ISSUE THREAD

**Issue by hectorromo** [wagnerwagner/merx#8]
Hi, and first of all nice plugin! :)

I’m moving a clients site to Kirby and Merx. The thing is that their site has more than 10 000 orders, and I’m wondering if it can be too much if I put all the orders under the same folder from a performance-perspective. The orders will of course only be for internal use so there will not be a lot of requests on that.
So my question is if you guys have any experience of sites with a lot of orders or any suggestion of what could be best way to handle this, like storing orders in db.

Thanks

**Comment by tobiasfabian** [comment]
Unfortunately none of our online shops has more than 10 000 orders (yet). So I can't give you a definite answer on this.

Your question does not only relate to Merx. Since _Merx orders_ are _Kirby pages_ the question should be, can Kirby handle 10 000 pages. As far as I know Kirby can get slow if there are many direct children. But there are ways around that. For example you could group orders in subdirectory. E.g. `2020/05/abcxyc/order.txt`

Apart from that. I think as long as these orders are not queried, 10 000 order pages won’t affect the general performance of the site.

Let us know when you've tested it.

**Comment by hectorromo** [comment]
Thanks @tobiasfabian. I'll try it out :). 
Closing this since it's more related to what Kirby can handle.

**Comment by hectorromo** [comment]
**Update:**
So, I've migrated the site to Kirby and Merx and must say that I'm surprised. I have grouped existing orders by month. Some months have up to 1000 orders, and it still works good. Good job wagnerwagner for making an easy and flexible plugin.
